<a href="https://colab.research.google.com/github/sadevans/RLT.Hack/blob/main/rlt_hack.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

In [85]:
import datetime as dt

In [29]:
rk_budj = pd.read_excel('Рекламные расходы и utm-метки.xlsx', sheet_name = 'РК Бюджет') #бюджет

In [27]:
chan = pd.read_excel('Рекламные расходы и utm-метки.xlsx', sheet_name = 'Каналы') #каналы

In [48]:
rk_budj

,Канал трафика,Январь,Февраль,Март,Апрель,Май,Июнь,Июль,Август,Сентябрь,Октябрь,Ноябрь,Декабрь
0,"Я.Директ,р",95000,123302,195000,150000,530222,42000,302111,304223,30000,304923,402934,312432
1,"VK, таргетинг,р",50323,60323,39429,15341,202341,195493,139248,431357,234098,210928,22145,90232
2,"СЕО Специалист, зп",100000,100000,100000,100000,100000,100000,100000,100000,100000,100000,100000,100000
3,"СЕО, внешнее продвижение,р",50320,43212,65432,49126,32945,98421,48732,102938,75162,56124,60981,38475
4,"Email-рассылка, сервис,р",95000,95000,95000,95000,95000,95000,95000,95000,95000,95000,95000,95000
5,"whatsapp, рассылка,р",24938,24938,24938,34938,34162,35871,23987,37817,64982,16827,21827,0
6,"СЕО, контенкт,р",35000,35000,35000,35000,35000,35000,35000,35000,54000,54000,54000,54000
7,"Я.Дзен,р",0,0,0,0,0,0,500000,300000,0,0,0,0
8,"Промо-материалы,р",0,200000,0,0,0,0,0,350000,0,0,0,0
9,"Партнерский маркетинг,р",0,50123,96000,87019,34987,105938,110293,98712,140329,150298,140393,87238
10,"VK, smm,р",20000,20000,20000,20000,20000,20000,25000,25000,25000,25000,25000,25000
11,"Колтреккинг,р",75000,75000,75000,75000,75000,75000,75000,75000,75000,75000,75000,75000
12,"Трафик менеджер,р",80000,80000,80000,80000,80000,80000,80000,80000,80000,80000,80000,120000
13,"SMM, специалист",60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,80000

In [31]:
chan

,Канал трафика,UTM_Source,Оператор,UTM Medium
0,"Я.Директ,р","yandex, yandex-search, yandex-network, direct,...",и,"cpc, cpa"
1,"VK, таргетинг,р","vkontakte, Telegram, etp_roseltorg",-,NaN
2,"СЕО Специалист, зп",NaN,-,NaN
3,"СЕО, внешнее продвижение,р",NaN,-,NaN
4,"Email-рассылка, сервис,р","mindbox, email, emarsys",или,mail
5,"whatsapp, рассылка,р",sms,или,CoMagic
6,"СЕО, контенкт,р",NaN,-,organic
7,"Я.Дзен,р","yandex.promopages, dzen_suggest_ad_priority, d...",-,NaN
8,Реферальный трафик,NaN,-,referral
9,"Промо-материалы,р","push, posteruc, qr, QR, vebinar, booklet,",-,NaN
10,"Партнерский маркетинг,р","gos.roseltorg.ru, com.roseltorg.ru, 178fz, flo...",-,NaN
11,"VK, smm,р",NaN,-,NaN
12,"Колтреккинг,р",NaN,-,NaN
13,"Трафик менеджер,р",NaN,-,NaN
14,"SMM, специалист",NaN,-,NaN

что делать с оператором ?

In [32]:
chan[chan['Канал трафика'] == 'Я.Директ,р'].UTM_Source[0]

'yandex, yandex-search, yandex-network, direct, yandex-direct'

In [34]:
prod = pd.read_excel('Продажи 2022 год УЦ_final.xlsx', sheet_name = 'Продажи') #продажи загрузили

In [49]:
prod.head()

,Номер заявки,Время и дата подачи заявки,Стоимость услуги,Тариф,Количество единиц услуги,Сумма НДС,"ФИО ответственного, получившего оплату (Продажники)",Агенты,"ФИО ответственного, получившего оплату (УЦ)",utm_source,utm_medium
0,1583146,17.11.2022 12:37:04,58800.0,Носитель Rutoken Lite (Стандарт),56,9800.0,NaN,NaN,Уц 21,NaN,NaN
1,1621163,16.12.2022 13:36:37,58800.0,Носитель Rutoken Lite (Стандарт),56,9800.0,NaN,NaN,Уц 21,NaN,NaN
2,1626900,22.12.2022 10:51:37,55000.0,"Комплект ""Основа"" квалифицированный, Без лицен...",55,NaN,NaN,Агент 1,NaN,google,organic
3,1192033,08.07.2022 07:05:28,52500.0,Носитель Rutoken Lite (Стандарт),35,8750.0,NaN,NaN,Уц 44,google,organic
4,1191694,07.07.2022 15:28:53,52500.0,Носитель Rutoken Lite (Стандарт),50,8750.0,NaN,NaN,Уц 69,google,organic

In [93]:
prod['Время и дата подачи заявки'] = pd.to_datetime(prod['Время и дата подачи заявки']).dt.date

In [94]:
prod.head()

,Номер заявки,Время и дата подачи заявки,Стоимость услуги,Тариф,Количество единиц услуги,Сумма НДС,"ФИО ответственного, получившего оплату (Продажники)",Агенты,"ФИО ответственного, получившего оплату (УЦ)",utm_source,utm_medium,Канал трафика
0,1583146,2022-11-17,58800.0,Носитель Rutoken Lite (Стандарт),56,9800.0,NaN,NaN,Уц 21,NaN,NaN,None
1,1621163,2022-12-16,58800.0,Носитель Rutoken Lite (Стандарт),56,9800.0,NaN,NaN,Уц 21,NaN,NaN,None
2,1626900,2022-12-22,55000.0,"Комплект ""Основа"" квалифицированный, Без лицен...",55,NaN,NaN,Агент 1,NaN,google,organic,"СЕО, контенкт,р"
3,1192033,2022-08-07,52500.0,Носитель Rutoken Lite (Стандарт),35,8750.0,NaN,NaN,Уц 44,google,organic,"СЕО, контенкт,р"
4,1191694,2022-07-07,52500.0,Носитель Rutoken Lite (Стандарт),50,8750.0,NaN,NaN,Уц 69,google,organic,"СЕО, контенкт,р"

надо замэпить данные по source и medium, чтобы получить итоговую табличку продаж с каналами

In [51]:
prod['Канал трафика'] = None

In [53]:
# prod.head()

In [59]:
chan.UTM_Source.unique()

array(['yandex, yandex-search, yandex-network, direct, yandex-direct',
       'vkontakte, Telegram, etp_roseltorg', nan,
       'mindbox, email, emarsys', 'sms',
       'yandex.promopages, dzen_suggest_ad_priority, dzen, dzen_suggest_nav_priority',
       'push, posteruc, qr, QR, vebinar,  booklet, ',
       'gos.roseltorg.ru, com.roseltorg.ru, 178fz, flocktory, partner'],
      dtype=object)

In [63]:
prod.utm_medium.unique()

array([nan, 'organic', 'referral', '(none)', 'cpc', 'call_centr',
       'workflow_push', 'duc', 'push_api', 'top', 'ng_2022',
       'raut_0911_tg_rb', 'torgi_auto', 'email', 'kuc',
       'mailnotification', 'popup', 'new-user', 'ng_2022_podarok',
       'webinar_uc_0507', 'digest91', 'uvedomlenie_ob_oplate_scheta_new',
       'banner', 'ep_ne_ip_dost', 'eis_speed_trigger', 'uvedomlenie_top',
       'akciya_20_bid', 'uc_2022_video', 'refferal', 'digest89', 'flyer',
       'autorun', 'video', 'nopaid', 'webinar_ep2022', 'alert',
       'digestN20', 'content_link', 'uvedomlenie_ob_oplate_scheta_new_2',
       'bg', 'digest81', 'akciya_40_20', 'ep_ip', 'digest80',
       'priglashenie_na_zakupku', 'cpa', 'uvedomlenie_ep_2_skidka5',
       'predlozhenie_komplekta_ep_3', 'uvedomlenie_o_poluchenii_uslugi',
       'procedure_info', 'importozam_post'], dtype=object)

In [57]:
[s.split(', ') for s in chan['UTM_Source'].unique() if type(s) is not float]

[['yandex', 'yandex-search', 'yandex-network', 'direct', 'yandex-direct'],
 ['vkontakte', 'Telegram', 'etp_roseltorg'],
 ['mindbox', 'email', 'emarsys'],
 ['sms'],
 ['yandex.promopages',
  'dzen_suggest_ad_priority',
  'dzen',
  'dzen_suggest_nav_priority'],
 ['push', 'posteruc', 'qr', 'QR', 'vebinar', ' booklet', ''],
 ['gos.roseltorg.ru', 'com.roseltorg.ru', '178fz', 'flocktory', 'partner']]

In [58]:
[s.split(', ') for s in chan['UTM Medium'].unique() if type(s) is not float]

[['cpc', 'cpa'], ['mail'], ['CoMagic'], ['organic'], ['referral']]

а как мэпить то....
можно сделать цикл в цикле, но для 300+к строк это дофига

In [ ]:
#channels = []

In [ ]:
#[channels.append(row['Канал трафика']) for index, row in chan]

In [65]:
prod.loc[prod['utm_source'].isin(['vkontakte', 'Telegram', 'etp_roseltorg']), 'Канал трафика'] = 'VK, таргетинг,р'
prod.loc[prod['utm_source'].isin(['push', 'posteruc', 'qr', 'QR', 'vebinar', ' booklet', '']), 'Канал трафика'] = 'Промо-материалы,р'
prod.loc[prod['utm_source'].isin(['gos.roseltorg.ru', 'com.roseltorg.ru', '178fz', 'flocktory', 'partner']), 'Канал трафика'] = 'Партнерский маркетинг,р'
prod.loc[prod['utm_source'].isin(['yandex.promopages', 'dzen_suggest_ad_priority', 'dzen', 'dzen_suggest_nav_priority']), 'Канал трафика'] = 'Я.Дзен,р'
prod.loc[prod['utm_source'].isin(['mindbox', 'email', 'emarsys']) | (prod['utm_medium'].isin(['email', 'mail'])), 'Канал трафика'] = 'Email-рассылка, сервис,р'
prod.loc[prod['utm_source'].isin(['sms']) | (prod['utm_medium'].isin(['CoMagic'])), 'Канал трафика'] = 'whatsapp, рассылка,р'
prod.loc[prod['utm_source'].isin(['yandex', 'yandex-search', 'yandex-network', 'direct', 'yandex-direct']) & (prod['utm_medium'].isin(['cpc', 'cpa'])), 'Канал трафика'] = 'Я.Директ,р'
prod.loc[prod['utm_medium'].isin(['organic']), 'Канал трафика'] = 'СЕО, контенкт,р'
prod.loc[prod['utm_medium'].isin(['referral']), 'Канал трафика'] = 'Реферальный трафик'
prod.loc[prod['utm_source'].isin([('(direct')]) & (prod['utm_medium'].isin(['(none)'])), 'Канал трафика'] = 'Прямой трафик'

In [66]:
prod

,Номер заявки,Время и дата подачи заявки,Стоимость услуги,Тариф,Количество единиц услуги,Сумма НДС,"ФИО ответственного, получившего оплату (Продажники)",Агенты,"ФИО ответственного, получившего оплату (УЦ)",utm_source,utm_medium,Канал трафика
0,1583146,17.11.2022 12:37:04,58800.0,Носитель Rutoken Lite (Стандарт),56,9800.0,NaN,NaN,Уц 21,NaN,NaN,None
1,1621163,16.12.2022 13:36:37,58800.0,Носитель Rutoken Lite (Стандарт),56,9800.0,NaN,NaN,Уц 21,NaN,NaN,None
2,1626900,22.12.2022 10:51:37,55000.0,"Комплект ""Основа"" квалифицированный, Без лицен...",55,NaN,NaN,Агент 1,NaN,google,organic,"СЕО, контенкт,р"
3,1192033,08.07.2022 07:05:28,52500.0,Носитель Rutoken Lite (Стандарт),35,8750.0,NaN,NaN,Уц 44,google,organic,"СЕО, контенкт,р"
4,1191694,07.07.2022 15:28:53,52500.0,Носитель Rutoken Lite (Стандарт),50,8750.0,NaN,NaN,Уц 69,google,organic,"СЕО, контенкт,р"
...,...,...,...,...,...,...,...,...,...,...,...,...
38833,1599666,30.11.2022 14:13:26,500.0,"Комплект ""Основа"" квалифицированный только для...",1,NaN,Менеджер 32,NaN,NaN,(direct),(none),None
38834,1599652,30.11.2022 14:07:24,500.0,"Комплект ""Основа"" квалифицированный только для...",1,NaN,Менеджер 32,NaN,NaN,(direct),(none),None
38835,1599630,30.11.2022 13:59:57,500.0,"Комплект ""Основа"" квалифицированный только для...",1,NaN,Менеджер 32,NaN,NaN,(direct),(none),None
38836,1599613,30.11.2022 13:54:18,500.0,"Комплект ""Основа"" квалифицированный только для...",1,NaN,Менеджер 32,NaN,NaN,(direct),(none),None
38837,1599588,30.11.2022 13:45:35,500.0,"Комплект ""Основа"" квалифицированный только для...",1,NaN,Менеджер 53,NaN,NaN,google,organic,"СЕО, контенкт,р"

In [68]:
#prod.dropna(subset= ['Канал трафика'])

In [70]:
#prod.dropna(subset= ['Канал трафика']).shape[0]

In [71]:
prod.dropna(subset= ['Канал трафика']).shape[0] / prod.shape[0] * 100  #процент заполненных ячеек канала

65.75776301560327

In [40]:
traff = pd.read_csv('traff_ga.csv', sep = ';')

In [41]:
traff

,ga_user_id,fullReferrer,source,medium,sessions,date
0,ga_user_id_1,(direct),(direct),(none),1,01.01.2022
1,ga_user_id_2,(direct),(direct),(none),1,01.01.2022
2,ga_user_id_3,(direct),(direct),(none),2,01.01.2022
3,ga_user_id_4,(direct),(direct),(none),1,01.01.2022
4,ga_user_id_5,(direct),(direct),(none),1,01.01.2022
...,...,...,...,...,...,...
540775,ga_user_id_394593,yandex.ru/,yandex.ru,referral,2,01.01.2023
540776,ga_user_id_395505,yandex.ru/,yandex.ru,referral,2,01.01.2023
540777,ga_user_id_396896,yandex.ru/,yandex.ru,referral,2,01.01.2023
540778,ga_user_id_279095,yandex.ru/,yandex.ru,referral,2,01.01.2023
540779,ga_user_id_395534,yandex.ru/,yandex.ru,referral,2,01.01.2023

In [95]:
traff['date'] = pd.to_datetime(traff['date']).dt.date

In [96]:
traff.head()

,ga_user_id,fullReferrer,source,medium,sessions,date,Канал трафика
0,ga_user_id_1,(direct),(direct),(none),1,2022-01-01,None
1,ga_user_id_2,(direct),(direct),(none),1,2022-01-01,None
2,ga_user_id_3,(direct),(direct),(none),2,2022-01-01,None
3,ga_user_id_4,(direct),(direct),(none),1,2022-01-01,None
4,ga_user_id_5,(direct),(direct),(none),1,2022-01-01,None

In [42]:
traff.fullReferrer.unique() #уникальные значения ищем

array(['(direct)', 'azbukatenderov-ru.turbopages.org/',
       'bankrupt.alfalot.ru/public/help/eds/', ..., 'vologda.ru/',
       'вологда.рф/', 'нижнийновгород.рф/Biznesu/tenders'], dtype=object)

In [46]:
traff.groupby(['source']).sum()

                                  sessions
source
(direct)                            153693
(not set)                               56
0.0.0.0:9000                             4
0558484.bitrix24.ru                      2
1                                        6
...                                    ...
нигма.рус                                1
нижнийновгород.рф                        5
новгородоблэлектро.рф                    1
спроси-дом-рф.cdn.ampproject.org        19
спроси.дом.рф                           39

[1231 rows x 1 columns]

In [72]:
traff['Канал трафика'] = None

In [74]:
traff.loc[traff['source'].isin(['vkontakte', 'Telegram', 'etp_roseltorg']), 'Канал трафика'] = 'VK, таргетинг,р'
traff.loc[traff['source'].isin(['push', 'posteruc', 'qr', 'QR', 'vebinar', ' booklet', '']), 'Канал трафика'] = 'Промо-материалы,р'
traff.loc[traff['source'].isin(['gos.roseltorg.ru', 'com.roseltorg.ru', '178fz', 'flocktory', 'partner']), 'Канал трафика'] = 'Партнерский маркетинг,р'
traff.loc[traff['source'].isin(['yandex.promopages', 'dzen_suggest_ad_priority', 'dzen', 'dzen_suggest_nav_priority']), 'Канал трафика'] = 'Я.Дзен,р'
traff.loc[traff['source'].isin(['mindbox', 'email', 'emarsys']) | (traff['medium'].isin(['email', 'mail'])), 'Канал трафика'] = 'Email-рассылка, сервис,р'
traff.loc[traff['source'].isin(['sms']) | (traff['medium'].isin(['CoMagic'])), 'Канал трафика'] = 'whatsapp, рассылка,р'
traff.loc[traff['source'].isin(['yandex', 'yandex-search', 'yandex-network', 'direct', 'yandex-direct']) & (traff['medium'].isin(['cpc', 'cpa'])), 'Канал трафика'] = 'Я.Директ,р'
traff.loc[traff['medium'].isin(['organic']), 'Канал трафика'] = 'СЕО, контенкт,р'
traff.loc[traff['medium'].isin(['referral']), 'Канал трафика'] = 'Реферальный трафик'
traff.loc[traff['source'].isin([('(direct')]) & (traff['medium'].isin(['(none)'])), 'Канал трафика'] = 'Прямой трафик'

In [75]:
traff

,ga_user_id,fullReferrer,source,medium,sessions,date,Канал трафика
0,ga_user_id_1,(direct),(direct),(none),1,01.01.2022,None
1,ga_user_id_2,(direct),(direct),(none),1,01.01.2022,None
2,ga_user_id_3,(direct),(direct),(none),2,01.01.2022,None
3,ga_user_id_4,(direct),(direct),(none),1,01.01.2022,None
4,ga_user_id_5,(direct),(direct),(none),1,01.01.2022,None
...,...,...,...,...,...,...,...
540775,ga_user_id_394593,yandex.ru/,yandex.ru,referral,2,01.01.2023,Реферальный трафик
540776,ga_user_id_395505,yandex.ru/,yandex.ru,referral,2,01.01.2023,Реферальный трафик
540777,ga_user_id_396896,yandex.ru/,yandex.ru,referral,2,01.01.2023,Реферальный трафик
540778,ga_user_id_279095,yandex.ru/,yandex.ru,referral,2,01.01.2023,Реферальный трафик
540779,ga_user_id_395534,yandex.ru/,yandex.ru,referral,2,01.01.2023,Реферальный трафик

In [76]:
traff.dropna(subset= ['Канал трафика']).shape[0] / traff.shape[0] * 100  #процент заполненных ячеек канала

74.05895188431525

In [84]:
# traff['Канал трафика'].nunique()
# traff.groupby('Канал трафика').nunique ()

,ga_user_id,fullReferrer,source,medium,sessions,date
Канал трафика,,,,,,
"Email-рассылка, сервис,р",9910,5,5,174,9,365
"VK, таргетинг,р",346,2,2,3,5,215
"whatsapp, рассылка,р",1,1,1,1,1,3
"Партнерский маркетинг,р",1704,4,4,10,7,322
"Промо-материалы,р",38,3,3,5,7,57
Реферальный трафик,157797,1597,1158,1,11,366
"СЕО, контенкт,р",138583,10,10,1,10,366
"Я.Дзен,р",96,2,2,3,3,19
"Я.Директ,р",2341,4,4,2,11,261

In [98]:
prod.to_excel('Продажи_2022_год_УЦ_with_channel.xlsx')
traff.to_excel('traff_ga_with_channel.xlsx')